### PR TITLE
Included gzip static module in nginx

### PR DESCRIPTION
**Pull request by ljfranklin**
Used to allow serving of precompiled gzip files. Generating .gz files at compile time is supported by popular static site generators like Middleman and Jekyll. 

Module must be included at nginx compile time. This feature can be invoked by adding ```gzip_static on;``` to nginx.conf.

### CODE REVIEW

**Comment by drnic** [comment]
@ljfranklin mate, I'm sorry I didn't review/merge this PR before @simonjohansson provided the trusty patch which involved changing the scripts.

@simonjohansson @ljfranklin are either of you available to rebase this branch & cut new nginx binaries?

See the https://github.com/cloudfoundry-incubator/staticfile-buildpack/blob/master/test/test.sh script for one method for checking if it doesn't break any of the test apps across the different stacks.

Add the stacks being tested to this list https://github.com/cloudfoundry-incubator/staticfile-buildpack/blob/master/test/test.sh#L13

**Comment by ljfranklin** [comment]
No problem @drnic. I'll give it a try in the next couple days.

**Comment by ljfranklin** [comment]
Updated with new binaries. Ran test.sh and all the test apps look fine.

**Comment by drnic** [comment]
Thanks!

**Pull request merged**
