### PR TITLE
Add support for cflinuxfs2 stack.

### LINKED ISSUE #26: Support for cflinuxfs2.
On a fresh CF 205 installation, 

```
$ mkdir /tmp/kehe && cf /tmp/kehe
$ touch Staticfile
$ cf push my-site -m 64M -b https://github.com/cloudfoundry-community/staticfile-buildpack.git -s cflinuxfs2
```
When cf logs my-site in another terminal I see

```
2015-03-26T15:59:42.68+0100 [App/0]      ERR /home/vcap/app/nginx/sbin/nginx: error while loading shared libraries: libssl.so.0.9.8: cannot open shared object file: No such file or directory
2015-03-26T15:59:42.71+0100 [DEA/1]      ERR Instance (index 0) failed to start accepting connections
```

Using the normal lucid64 stack works like a charm.

More info about cflinuxfs2, https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/gU7rpD8MSC

### PR DESCRIPTION
**Pull request by simonjohansson**
Verified against a newly deployed 205. 

Fixes #26

### CODE REVIEW

**Comment by drnic** [comment]
Is it also possible if you include the patches for using using the correct prebuilt nginx in bin/compile?

**Comment by simonjohansson** [comment]
Just quick and dirty.
We should probably have two machines in the Vagrant file, and also alter the build script to detect if we are buildling on trusty or lucid.

**Comment by simonjohansson** [comment]
Im sorry @drnic , I dont really understand what you mean.

**Comment by drnic** [comment]
Im ok with the build changes - these are for DIY builders. Would be great for the distributed buildpack to include the pre-compiled final results - lucid and trusty nginx compiled and ready to be selected in bin/compile

**Comment by simonjohansson** [comment]
Ah, I see what you mean.
Yeah, that makes sense. I shall fix.

**Comment by simonjohansson** [comment]
@drnic please have a look at the changes in case there is something improvments you can see.

**Comment by drnic** [comment]
Looks good at a glance. Will try to test and merge today.

Do we need the nginx tgz without a lucid/trusty in its name?

**Comment by drnic** [comment]
Or is that the source for compilation; sorry - hard to write msgs and re-look at PR via iPhone :)

**Comment by simonjohansson** [comment]
@drnic that was the old nginx used by warden container.
Ive removed that, and replaced with two new tars, one for lucid and one for trusty.

**Comment by drnic** [comment]
Ok. I misread the github notations in the changes - thought it was an added file

**Comment by drnic** [comment]
As a bonus, I've added more docs on how to manually test a buildpack PR/branch https://github.com/cloudfoundry-incubator/staticfile-buildpack#local-development

I'll automate it later :)

**Comment by drnic** [comment]
Thank you very much for trusty support!

**Comment by drnic** [comment]
@simonjohansson what is your twitter handle?

**Comment by drnic** [comment]
image

Hurray!

**Comment by simonjohansson** [comment]
Swell, @drnic :)

My twitter handler is @KarlSimonJohan

**Pull request merged**
