### PR TITLE
Adding support for custom 404 error pages.

### PR DESCRIPTION
**Pull request by troytop**
It's handy to have a way to specify custom error pages. Might consider a 403 page as well.

### CODE REVIEW

**Comment by troytop** [comment]
Just occured to me, should this be settable in `Staticfile` as well?

**Comment by drnic** [comment]
Yeah agreed - do configuration in Staticfile. Thanks for the PR!

**Comment by drnic** [comment]
Yeah agreed - do configuration in Staticfile. Thanks for the PR!

**Comment by skibz** [comment]
what's the status of this addition?
would love to have this landed :) :+1:

**Comment by troytop** [comment]
Sorry I haven't had time to add the Staticfile setting option. If anyone else has the cycles, go for it.

**Comment by skibz** [comment]
nooooo dont close :(

**Comment by drnic** [comment]
I can't reopen the PR. perhaps create a new issue.

**Comment by troytop** [comment]
Sorry, I dropped the changes from our fork by mistake when trying to get back to something I can test with on Stackato (currently broken by https://github.com/cloudfoundry-incubator/staticfile-buildpack/commit/0d05afa88f80d343ed6e13f5f348942a02302087 as we use a 'precise' stack). I still have them and will resubmit with.

**Pull request closed without merging**
